---

stages:
- build

build:
  stage: build
  image: nixos/nix
  variables:
  before_script:
  - export NIX_HOME="${HOME}/.config/nixpkgs"
  - nix-channel --add https://nixos.org/channels/nixos-20.03 nixpkgs
  - nix-channel --add https://github.com/rycee/home-manager/archive/release-20.03.tar.gz home-manager
  - nix-channel --update
  - nix-shell '<home-manager>' -A install
  - rm ${NIX_HOME}/home.nix
  - ln -s ${NIX_HOME}/home.nix $(pwd)/home.nix
  script:
  - home-manager build
