image: nixos/nix:latest

build:
  before_script:
  - nix-env -iA nixpkgs.cachix nixpkgs.bash
  - cachix use nobbz
  - nix path-info --all > /tmp/store-path-pre-build
  script:
  - |
    set -x
    for file in hosts/*.nix; do
      host=$(basename $file .nix)
      ln -s $host.nix hosts/default.nix
      nix-shell --run "home-manager -v build"
      mv result $host.result
      nix-store --indirect --add-root $(pwd)/$host.result
      rm hosts/default.nix
    done
    nix-collect-garbage --verbose
  after_script:
  - bash -c "comm -13 <(sort /tmp/store-path-pre-build | grep -v '\.drv$') <(nix path-info --all | grep -v '\.drv$' | sort) | cachix push nobbz"
