---

stages:
- build

build:
  stage: build
  image: nixos/nix
  variables:
    NIX_HOME: "$HOME/.config/nixpkgs"
  before_script:
  - nix-channel --add https://nixos.org/channels/nixos-20.03 nixpkgs
  - nix-channel --add https://github.com/rycee/home-manager/archive/release-20.03.tar.gz home-manager
  - nix-channel --update
  - nix-shell '<home-manager>' -A install
  - printenv HOME
  - printenv NIX_HOME
  script:
  - home-manager build
