---
name: "preflight"

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  lint:
    name: "Preflight – Linting"
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        package:
        - advcp
        - elixir-lsp
        - erlang-ls
        - keyleds
        - rofi-unicode
        - nix-zsh-completions
        - keepass
        - julia_10
        - julia_13
        - julia_15
    steps:
    - uses: actions/checkout@v2.3.1
      with: { fetch-depth: 0 }
    - uses: cachix/install-nix-action@v12
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20200820_4d77513/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - run: nix build .#${{ matrix.package }}
